name: Cube-Lanta
main: fr.xninja.cubelanta.CubeLanta
version: 0.01
author: 0xNinja

commands:
  #to remove
  changeteam:
    description: aze
    usage: /<command> <team>

  # Cube-Lanta commands
  setinterview:
    description: Set the interviews' location at your actual location, and set interviewed's location with x y and z
    usage: /<command> x y z

  interview:
    description: Schedule an interview with a player in <minutes> minutes or stop a running interview
    usage: /<command> start <player> <minutes> | /command stop

  setup:
    description: Setup the Cube-Lanta experience
    usage: /<command> <yellow team name> <red team name> <white team name>
    
  role:
    description: Get a player's role
    usage: /<command>
